version: '3.8'

services:
  backend:
    build: ./backend
    container_name: springboot-backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/assignment
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: apppass

  template:
    build: ./template
    container_name: static-template
    ports:
      - "3000:80"
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: assignment
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - app-network

networks:
  app-network:

volumes:
  mysql-data:
